#För att det ska funka med extern access behövs även en ingress och en ingress-controller. Ingress är (nog) ett kubernetes-objekt som definierar ingress:en, och ingress-controller är (nog) själva servern som tar emot tcp-anrop utifrån. Se https://kubernetes.io/docs/concepts/services-networking/ingress/

---

apiVersion: v1
kind: Service
metadata:
  name:  web-port
spec:
  selector:
    app:  tomcat
  ports:
  - name:  web-server-port
    port:  80
    targetPort:  8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
